/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ImagenFondo;
import Logica.conexion;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.sql.Connection;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.border.Border;

/**
 *
 * @author Justino
 */
public class frminicio extends javax.swing.JFrame implements Runnable{
    String hora, minutos, segundos, ampm;
    Calendar calendario;
    Thread h1;

    /**
     * Creates new form frminicio
     */
    public frminicio() {
        initComponents();
        this.setExtendedState(frminicio.MAXIMIZED_BOTH);
        this.setTitle("MENU DEL SISTEMA");
        
      h1 = new Thread(this);
      h1.start();
        setLocationRelativeTo(null);//para centrar la ventana
        setVisible(true);
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        lblidusuario = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lblacceso = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        fac = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuregistroproducto = new javax.swing.JMenuItem();
        menuregistromarca = new javax.swing.JMenuItem();
        menupermisosyaccesos = new javax.swing.JMenu();
        menuaccesos = new javax.swing.JMenuItem();
        menureportes = new javax.swing.JMenu();
        menupersona = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setForeground(new java.awt.Color(0, 0, 0));

        lblidusuario.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblidusuario.setForeground(new java.awt.Color(255, 255, 255));
        lblidusuario.setText("MUESTRA ID");
        lblidusuario.setRequestFocusEnabled(false);
        Escritorio.add(lblidusuario);
        lblidusuario.setBounds(100, 50, 130, 30);

        lblapellido.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblapellido.setForeground(new java.awt.Color(255, 255, 255));
        lblapellido.setText("MUESTRA APELLIDO");
        Escritorio.add(lblapellido);
        lblapellido.setBounds(220, 170, 280, 30);

        lblacceso.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblacceso.setForeground(new java.awt.Color(255, 255, 255));
        lblacceso.setText("MUESTRA TIPO ACCESO");
        Escritorio.add(lblacceso);
        lblacceso.setBounds(220, 250, 310, 30);

        lblnombre.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        lblnombre.setText("MUESTRA NOMBRE");
        Escritorio.add(lblnombre);
        lblnombre.setBounds(220, 100, 230, 30);

        lblhora.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblhora.setForeground(new java.awt.Color(255, 255, 255));
        lblhora.setText("Muestra hora");
        Escritorio.add(lblhora);
        lblhora.setBounds(490, 570, 300, 90);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ACCESO:");
        Escritorio.add(jLabel1);
        jLabel1.setBounds(100, 240, 100, 50);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APELLIDO:");
        Escritorio.add(jLabel2);
        jLabel2.setBounds(100, 160, 100, 50);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USUARIO:");
        Escritorio.add(jLabel3);
        jLabel3.setBounds(100, 90, 100, 50);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Registrar Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventas");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        fac.setText("Generar Factura");
        fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facActionPerformed(evt);
            }
        });
        jMenu2.add(fac);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Inventario");

        menuregistroproducto.setText("Regstrar Producto");
        menuregistroproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuregistroproductoActionPerformed(evt);
            }
        });
        jMenu3.add(menuregistroproducto);

        menuregistromarca.setText("Registrar Marca");
        menuregistromarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuregistromarcaActionPerformed(evt);
            }
        });
        jMenu3.add(menuregistromarca);

        jMenuBar1.add(jMenu3);

        menupermisosyaccesos.setText("Accesos");

        menuaccesos.setText("Permisos y Accesos");
        menuaccesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuaccesosActionPerformed(evt);
            }
        });
        menupermisosyaccesos.add(menuaccesos);

        menureportes.setText("Reportes");
        menupermisosyaccesos.add(menureportes);

        menupersona.setText("Persona");
        menupersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupersonaActionPerformed(evt);
            }
        });
        menupermisosyaccesos.add(menupersona);

        jMenuBar1.add(menupermisosyaccesos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuaccesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuaccesosActionPerformed
        // TODO add your handling code here:
        frmusuarios form=new frmusuarios();
         Escritorio.add(form);
          form.toFront();
           form.setVisible(true);
          //new frmusuarios().setVisible(true);
    }//GEN-LAST:event_menuaccesosActionPerformed

    private void menupersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupersonaActionPerformed
        // TODO add your handling code here:
        frmpersona form=new frmpersona();
         Escritorio.add(form);
          form.toFront();
           form.setVisible(true);
        
    }//GEN-LAST:event_menupersonaActionPerformed

    private void menuregistroproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuregistroproductoActionPerformed
        // TODO add your handling code here:
        frmproducto form=new frmproducto();
         Escritorio.add(form);
          form.toFront();
           form.setVisible(true);
    }//GEN-LAST:event_menuregistroproductoActionPerformed

    private void menuregistromarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuregistromarcaActionPerformed
        // TODO add your handling code here:
         frmarca form=new frmarca();
         Escritorio.add(form);
          form.toFront();
           form.setVisible(true);
    }//GEN-LAST:event_menuregistromarcaActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facActionPerformed
        // TODO add your handling code here:
          frmfactura form=new frmfactura();
         Escritorio.add(form);
          form.toFront();
           form.setVisible(true);
    }//GEN-LAST:event_facActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
          frmclientes form=new frmclientes();
         Escritorio.add(form);
          form.toFront();
           form.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frminicio().setVisible(true);
            }
        });
    }
    
    private conexion mysql=new conexion();
    private Connection cn=mysql.conectar();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem fac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JLabel lblacceso;
    public static javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblhora;
    public static javax.swing.JLabel lblidusuario;
    public static javax.swing.JLabel lblnombre;
    private javax.swing.JMenuItem menuaccesos;
    private javax.swing.JMenu menupermisosyaccesos;
    private javax.swing.JMenuItem menupersona;
    private javax.swing.JMenuItem menuregistromarca;
    private javax.swing.JMenuItem menuregistroproducto;
    private javax.swing.JMenu menureportes;
    // End of variables declaration//GEN-END:variables

    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            calcula();
            lblhora.setText(hora + ":" + minutos + ":" + segundos + " " + ampm);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }

    public void calcula() {
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();

        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";

        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);

}
  
    public BufferedImage back;
 
    public void ImagenFondo(){
        try {
            URL imagePath = new URL(getClass().getResource("../Fondo_inicio/casa stark 2560x1600.jpg").toString());
            back = ImageIO.read(imagePath);
        } catch (Exception ex) {            
        }
    }

    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        g.drawImage(back, (x + (width - back.getWidth())/2),(y + (height - back.getHeight())/2), null);
    }
 
    public Insets getBorderInsets(Component c) {
        return new Insets(0,0,0,0);
    }
 
    public boolean isBorderOpaque() {
        return false;
    }
}
