/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Servicios.ImagenFondo;
import Servicios.conexion;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.sql.Connection;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.border.Border;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Justino
 */
public class frminicio extends javax.swing.JFrame implements Runnable{
    String hora, minutos, segundos, ampm;
    Calendar calendario;
    Thread h1;

    /**
     * Creates new form frminicio
     */
    public frminicio() {
        initComponents();
        this.setExtendedState(frminicio.MAXIMIZED_BOTH);
        this.setTitle("MENU DEL SISTEMA");
        
      h1 = new Thread(this);
      h1.start();
        setLocationRelativeTo(null);//para centrar la ventana
        setVisible(true);
        lblimagen.setSize(1920, 1070);
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        lblidusuario = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lblacceso = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuarchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        fac = new javax.swing.JMenuItem();
        menuinventario = new javax.swing.JMenu();
        menuregistroproducto = new javax.swing.JMenuItem();
        menuregistromarca = new javax.swing.JMenuItem();
        menupermisosyaccesos = new javax.swing.JMenu();
        menuaccesos = new javax.swing.JMenuItem();
        menureportes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menupersona = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setForeground(new java.awt.Color(0, 0, 0));

        lblidusuario.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblidusuario.setForeground(new java.awt.Color(255, 255, 255));
        lblidusuario.setText("MUESTRA ID");
        lblidusuario.setRequestFocusEnabled(false);
        Escritorio.add(lblidusuario);
        lblidusuario.setBounds(50, 60, 130, 30);

        lblapellido.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblapellido.setForeground(new java.awt.Color(255, 255, 255));
        lblapellido.setText("MUESTRA APELLIDO");
        Escritorio.add(lblapellido);
        lblapellido.setBounds(110, 120, 280, 29);

        lblacceso.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblacceso.setForeground(new java.awt.Color(255, 255, 255));
        lblacceso.setText("MUESTRA TIPO ACCESO");
        Escritorio.add(lblacceso);
        lblacceso.setBounds(70, 170, 310, 29);

        lblnombre.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        lblnombre.setText("MUESTRA NOMBRE");
        Escritorio.add(lblnombre);
        lblnombre.setBounds(30, 120, 230, 30);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (2).png"))); // NOI18N
        Escritorio.add(jLabel2);
        jLabel2.setBounds(40, 20, 90, 100);

        lblhora.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lblhora.setForeground(new java.awt.Color(255, 255, 255));
        lblhora.setText("Muestra hora");
        Escritorio.add(lblhora);
        lblhora.setBounds(180, 570, 300, 90);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/candado.png"))); // NOI18N
        Escritorio.add(jLabel1);
        jLabel1.setBounds(30, 160, 40, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reloj.png"))); // NOI18N
        Escritorio.add(jLabel4);
        jLabel4.setBounds(40, 540, 130, 140);

        lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_inicio/fondo azul 2.png"))); // NOI18N
        Escritorio.add(lblimagen);
        lblimagen.setBounds(1, 0, 1680, 760);

        menuarchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivo.jpg"))); // NOI18N
        menuarchivo.setText("Archivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        jMenuItem1.setText("Registrar Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuarchivo.add(jMenuItem1);

        jMenuBar1.add(menuarchivo);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pago.png"))); // NOI18N
        jMenu2.setText("Ventas");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        fac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura.png"))); // NOI18N
        fac.setText("Generar Factura");
        fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facActionPerformed(evt);
            }
        });
        jMenu2.add(fac);

        jMenuBar1.add(jMenu2);

        menuinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura.png"))); // NOI18N
        menuinventario.setText("Inventario");

        menuregistroproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carro-de-entregas.png"))); // NOI18N
        menuregistroproducto.setText("Regstrar Producto");
        menuregistroproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuregistroproductoActionPerformed(evt);
            }
        });
        menuinventario.add(menuregistroproducto);

        menuregistromarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acuerdo.png"))); // NOI18N
        menuregistromarca.setText("Registrar Marca");
        menuregistromarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuregistromarcaActionPerformed(evt);
            }
        });
        menuinventario.add(menuregistromarca);

        jMenuBar1.add(menuinventario);

        menupermisosyaccesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administrador.png"))); // NOI18N
        menupermisosyaccesos.setText("Accesos");

        menuaccesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.png"))); // NOI18N
        menuaccesos.setText("Permisos y Accesos");
        menuaccesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuaccesosActionPerformed(evt);
            }
        });
        menupermisosyaccesos.add(menuaccesos);

        menureportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura.png"))); // NOI18N
        menureportes.setText("Reportes");

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menureportes.add(jMenuItem2);

        jMenuItem3.setText("Facturas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menureportes.add(jMenuItem3);

        jMenuItem4.setText("Productos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menureportes.add(jMenuItem4);

        menupermisosyaccesos.add(menureportes);

        menupersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        menupersona.setText("Persona");
        menupersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupersonaActionPerformed(evt);
            }
        });
        menupermisosyaccesos.add(menupersona);

        jMenuBar1.add(menupermisosyaccesos);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion-.png"))); // NOI18N
        jMenu1.setText("Configuracion");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen3.png"))); // NOI18N
        jMenuItem5.setText("Cambiar Fondo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1769, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facActionPerformed
        // TODO add your handling code here:
        frmfactura form=new frmfactura();
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_facActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menuregistroproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuregistroproductoActionPerformed
        // TODO add your handling code here:
        frmproducto form=new frmproducto();
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuregistroproductoActionPerformed

    private void menuregistromarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuregistromarcaActionPerformed
        // TODO add your handling code here:
        frmarca form=new frmarca();
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuregistromarcaActionPerformed

    private void menuaccesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuaccesosActionPerformed
        // TODO add your handling code here:
        frmusuarios form=new frmusuarios();
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
        //new frmusuarios().setVisible(true);
    }//GEN-LAST:event_menuaccesosActionPerformed

    private void menupersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupersonaActionPerformed
        // TODO add your handling code here:
        frmpersona form=new frmpersona();
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);

    }//GEN-LAST:event_menupersonaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frmclientes form=new frmclientes();
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
              try {
            conexion cc= new conexion();
            URL archivo = this.getClass().getResource("/reportes/clientes.jasper");
            JasperReport jr = null;            
            jr = (JasperReport) JRLoader.loadObject(archivo);
            JasperPrint jp = JasperFillManager.fillReport(jr,null,cc.conectar());
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setTitle("Clientes");
            
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
              try {
            conexion cc= new conexion();
            URL archivo = this.getClass().getResource("/reportes/facturas.jasper");
            JasperReport jr = null;            
            jr = (JasperReport) JRLoader.loadObject(archivo);
            JasperPrint jp = JasperFillManager.fillReport(jr,null,cc.conectar());
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setTitle("Clientes");
            
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
              try {
            conexion cc= new conexion();
            URL archivo = this.getClass().getResource("/reportes/productos.jasper");
            JasperReport jr = null;            
            jr = (JasperReport) JRLoader.loadObject(archivo);
            JasperPrint jp = JasperFillManager.fillReport(jr,null,cc.conectar());
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setTitle("Clientes");
            
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Configuracion conf = new Configuracion();
        conf.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frminicio().setVisible(true);
            }
        });
    }
    
    private conexion mysql=new conexion();
    private Connection cn=mysql.conectar();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem fac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    public static javax.swing.JLabel lblacceso;
    public static javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblhora;
    public static javax.swing.JLabel lblidusuario;
    public static javax.swing.JLabel lblimagen;
    public static javax.swing.JLabel lblnombre;
    public static javax.swing.JMenuItem menuaccesos;
    public static javax.swing.JMenu menuarchivo;
    public static javax.swing.JMenu menuinventario;
    public static javax.swing.JMenu menupermisosyaccesos;
    public static javax.swing.JMenuItem menupersona;
    private javax.swing.JMenuItem menuregistromarca;
    private javax.swing.JMenuItem menuregistroproducto;
    private javax.swing.JMenu menureportes;
    // End of variables declaration//GEN-END:variables

    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            calcula();
            lblhora.setText(hora + ":" + minutos + ":" + segundos + " " + ampm);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }

    public void calcula() {
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();

        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";

        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);

}
  
}
